name: embed
description: Code generation for embedding arbitrary file content into Dart code.
version: 1.2.0
repository: https://github.com/fujidaiti/embed.dart.git

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  analyzer: ">=5.2.0 <7.0.0"
  embed_annotation: ^1.2.0
  build: ^2.4.1
  source_gen: ^1.4.0
  path: ^1.8.3
  yaml: ^3.1.2
  recase: ^4.1.0
  toml: ^0.14.0
  meta: ^1.9.1
  collection: ^1.17.2

dependency_overrides:
  embed_annotation:
    path: ../embed_annotation

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.1.1
  mockito: ^5.4.2
  source_gen_test: ^1.0.6
  test: ^1.24.4
