name: embed
description: Code generation for embedding arbitrary file content into Dart code.
version: 1.6.0
repository: https://github.com/fujidaiti/embed.dart.git

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  analyzer: '>=7.4.0 <9.0.0'
  embed_annotation: ^1.2.2
  build: '>=3.0.0 <5.0.0'
  source_gen: '>=3.1.0 <5.0.0'
  path: ^1.9.1
  yaml: ^3.1.3
  recase: ^4.1.0
  toml: ^0.16.0
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.15
  mockito: ^5.4.5
  source_gen_test: ^1.1.1
  test: ^1.25.15
