name: embed_annotation
description: A package exposing annotations for embed.
version: 1.2.3
repository: https://github.com/fujidaiti/embed.dart.git

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace
