name: embed_annotation
description: A package exposing annotations for embed.
version: 1.2.0
repository: https://github.com/fujidaiti/embed.dart.git

environment:
  sdk: ">=3.0.5 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
